[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

[functions."rebuild-index"]
  timeout = 60

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
